version: "3.8"

volumes:
  pg_data:
  redis_data:

services:
  bot:
    hostname: bot-dev
    restart: unless-stopped
    build:
      # if use private libs uncomment this
      #      args:
      #        - GITHUB_TOKEN=${GITHUB_TOKEN}
      context: ./
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    ports:
      - 8888:${APP_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"